---
- name: show arrays
  hosts: ourselvesshelves.corp.ir2.yahoo.com
  vars_files:
    - vars/users
  tasks:
    - name: print array values
      debug:
        msg: "User {{ item.username }} has homedirectory {{ item.homedir }} and shell {{ item.shell }}"
      with_items: "{{ users }}"
