---
- name: test assert
  hosts: defendfriend.corp.ir2.yahoo.com
  tasks:
  - name: test assert
    assert:
      that:
        - ansible_ens34 is defined
      msg: bad luck dude
  - name: print text is assert did not fail
    debug:
      msg: ens33 exists

- name: second play
  hosts: defendfriend.corp.ir2.yahoo.com
  tasks:
  - name: placeholder
    debug:
      msg: this is part 2
