---
- name: test ftp upload
  hosts: localhost
  tasks:
  - name: install lftp
    yum:
      name: lftp
  - name: upload file
    shell: >
      lftp defendfriend.corp.ir2.yahoo.com <<EOF
      cd pub
      put /etc/hosts
      EOF
